name: arsenal_app
description: Arsenal application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI TOOLKIT
  cupertino_icons: ^0.1.3 # IOS
  flag: ^3.0.0 # Displaying flag icons
  circular_check_box: ^1.0.4 # Displaying circular check box
  qr_flutter: ^3.1.0 # Generate QR codes
  flutter_svg: ^0.19.3 # Displaying SVG files
  pin_code_fields: ^7.1.0 #reset password fields
  expandable: ^5.0.1 # Expandable containers

  # IMAGE PICKER
  path_provider: ^0.4.1
  image_picker: ^0.7.2+1

  # STATE MANAGEMENT
  provider: ^5.0.0
  hooks_riverpod: ^0.12.2 # Riverpod with hooks from Remi Rousselet
  flutter_hooks: ^0.15.0 # additional hooks' functionality
  equatable: ^2.0.0 # equatable annotations


  #NETWORKING
  dio: 4.0.0-beta7 # HTTP client with interceptors
  json_annotation: 3.1.1 # Defines the annotations used by json_serializable

  # LOCALIZATION
  easy_localization: ^3.0.0
  flutter_localizations:
    sdk: flutter
  number_display: # latest version

  # LOCAL STORAGE
  shared_preferences: ^2.0.5 # Shared preferences for storing smth

  # APPLICATION
  url_launcher: ^6.0.2 # Launch third-party app
  intl_phone_number_input: ^0.7.0+2
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.5 # generating files using Dart code
  json_serializable: 3.5.1 # Dart Build System builders for handling JSON

  # LINTER:
  #lint: ^1.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/auth/
    - assets/icons/
    - assets/images/
    - assets/splash/
    - i18n/uk-UA.json
    - i18n/ru-RU.json
    - i18n/en.json
    - i18n/en-EN.json

  fonts:
    - family: FrizQuadrataCTT
      fonts:
        - asset: assets/fonts/FrizQuadrataCTT.ttf

    - family: HelveticaRegular
      fonts:
        - asset: assets/fonts/HelveticaRegular.ttf